### ISSUE TITLE
Hosting location for summon app?

### ISSUE THREAD

**Issue by ppannuto** [lab11/polypoint#11]
This used to live on nuclear, but nuclear is no more:
```bash
$ cat publish.sh
#!/usr/bin/env bash

scp -r cordova.js cordova_plugins.js css img index.html js plugins nuclear.eecs.umich.edu:/opt/public/ble/tritag/
```

@bradjc @brghena @tzachari this may be a more general problem for summon apps, or is this solved already and I just need to push this app somewhere else?

**Comment by bradjc** [comment]
We use github now via j2x.us

**Comment by tzachari** [comment]
I believe it's hosted via rawgit: [http://j2x.us/Edukt0](http://j2x.us/Edukt0)

**Comment by ppannuto** [comment]
Great. I was pretty sure this wasn't a problem but doubted myself.
