### ISSUE TITLE
[Feature] Localization of any number of tags at high frequency

### ISSUE THREAD

**Issue by AlexisTM** [lab11/polypoint#13]
Did you consider implementing a GPS like protocol for the DWM1000?

This requires:
* Synchronizing the timestamps of all devices;
* Each anchor send its position and current timestamp;
* From the positions and timestamps received, the devices compute their position.

Pros:
* Works with any number of tags are they are in "listening only" mode;
* Adding an anchor do not require to change the configuration of each tag;
* The tags are "stupid" and thus do not need more configuration than the band, power, ... and can join any network seamlessly.

Cons: 
* The timestamp synchronization must be precise;
* The anchors must send their messages in a synchronous way.

**Comment by ppannuto** [comment]
It's a neat concept, but we haven't really pursed this. The biggest challenge is the time synchronization part. At the speed of light, 1 ns of time offset is ~30cm of range error. The best we've been able to synchronize a network of anchors (using DecaWave alone) is a few ns for one-hop neighbors and 10s of ns for two hop neighbors (see Fig 3 of https://patpannuto.com/pubs/kempke16surepoint.pdf).

Using an external synchronization mechanism, or maybe even a novel RF synchronization protocol, could be a cool way to enable things here, but it's not immediately obvious how to realize sufficiently high fidelity RF synchronization.

**Comment by AlexisTM** [comment]
Outdated.
