### ISSUE TITLE
Ranges are often reported as -2 million meters

### ISSUE THREAD

**Issue by bpkempke** [lab11/polypoint#6]

**Comment by bradjc** [comment]
I believe that is an error code.

https://github.com/lab11/polypoint/blob/master/software/firmware/oneway_tag.h#L24

**Comment by bpkempke** [comment]
This issue has been solved with commit c34a247d83d63a63692f4040b74ec41144df9d68.  It turns out that if you receive a message too quickly after configuring the receiver, the incoming packet data will contain a variety of bit-shifted portions of the last received packet.  Padding has been applied to the beginning and end of the ranging response windows to avoid this.

**Comment by bradjc** [comment]
I'm glad you found and solved this. I saw this happen and thought I was crazy because what chip messes up bits in bytes over SPI?
